apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-microservices-to-vault
  namespace: esprit-portail-entreprise-dev
spec:
  podSelector:
    matchLabels:
      app: portail-entreprise
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: vault
      ports:
        - protocol: TCP
          port: 8200